### PR TITLE
Add separate Ukrainian text to Weslogo-text.svg

### PR DESCRIPTION
**Pull request by archdron**
Added separate Ukrainian text instead of relying on Russian.
The font used is [Rutenia Decor](https://abetkarutenia.com.ua/product/ruteniadecor/), available under the [Creative Commons](https://creativecommons.org/licenses/by-sa/4.0/deed.uk) [Attribution-Share Alike 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license.

### CODE REVIEW

**Comment by archdron** [comment]
Had to close to double check, reopening.

**Comment by archdron** [comment]
Had to close to double check, reopening.

**Comment by Pentarctagon** [comment]
@amakriLexa04 does this look good to you?

**Comment by amakriLexa04** [comment]
Archdron is a member of Ukrainian translation team and is my right hand, so I have no doubts about the quality of his work on this PR.

Our top priority now is to get as far away from resources of russian translation as possible (previously Ukrainian translation used russian maps and logos), so I welcome his plans to change the logo, as it is the last thing left from the old days. 

We also plan to do a PR with the new logo, some maps and other translated images soon.

**Pull request merged**
